// Flow generators (§14–§16). Given a built kit, produce:
//   • describeKit(kit)  — the raw structural snapshot (delegates to kit.describe()).
//   • toFlowGraph(kit)  — a { nodes, edges } graph in the FlowNode/FlowEdge
//                         vocabulary, so it can be diffed against a hand-authored
//                         manifest or fed to React Flow.
//   • toFlowYaml(kit)   — the human-readable, diff-friendly committed document,
//                         event-centric, with a @generated banner.
// All three are pure: they run nothing on the kit but a read-only registry walk.
import type { EventKit, FlowEdge, FlowNode, KitDescription } from '../core/index.js';
import { toYaml } from './yaml.js';

/** The structural snapshot of a built kit. */
export function describeKit(kit: EventKit): KitDescription {
  return kit.describe();
}

const SOURCE_ID = 'source';
const eventId = (name: string): string => `event:${name}`;
const jobId = (event: string, job: string): string => `job:${event}:${job}`;
const sideEffectId = (job: string, effect: string): string => `sideEffect:${job}:${effect}`;

/**
 * A `{ nodes, edges }` graph in the manifest vocabulary: one `source` node, an
 * `event` node per registered event (edge source→event), a `job` node per job
 * (edge event→job), and a `sideEffect` node for any job declaring
 * `metadata.sideEffect` (edge job→sideEffect). Node ids are derived from
 * event/job names (never file paths), so they are stable across refactors (§14).
 */
export function toFlowGraph(kit: EventKit): { nodes: FlowNode[]; edges: FlowEdge[] } {
  const d = kit.describe();
  const nodes: FlowNode[] = [{ id: SOURCE_ID, kind: 'source', sourceFunction: d.source.name }];
  const edges: FlowEdge[] = [];

  for (const ev of d.events) {
    const evId = eventId(ev.name);
    const evNode: FlowNode = { id: evId, kind: 'event', eventName: ev.name };
    if (ev.flowHints) evNode.metadata = { flowHints: ev.flowHints };
    nodes.push(evNode);
    edges.push({ from: SOURCE_ID, to: evId });

    for (const j of ev.jobs) {
      const jId = jobId(ev.name, j.name);
      nodes.push({ id: jId, kind: 'job', jobName: j.name });
      // continueOnFailure:false marks a job the run treats as required (stops the batch).
      edges.push(j.continueOnFailure === false ? { from: evId, to: jId, required: true } : { from: evId, to: jId });

      const effect = j.metadata?.['sideEffect'];
      if (typeof effect === 'string' && effect) {
        const seId = sideEffectId(j.name, effect);
        nodes.push({ id: seId, kind: 'sideEffect', metadata: { sideEffect: effect } });
        edges.push({ from: jId, to: seId });
      }
    }
  }

  return { nodes, edges };
}

const BANNER = [
  '# @generated by @hopdrive/eventkit/flow — DO NOT EDIT BY HAND.',
  '# Regenerate with:  npx eventkit-flow generate --kit <module> --out <file>',
  '# CI drift check:   npx eventkit-flow check    --kit <module> --out <file>',
  '#',
  '# Documents the STRUCTURE of events registered on the kit (source -> event -> jobs),',
  '# derived from the declarative modules. Business MEANING (cross-event chains, intent)',
  '# belongs in a hand-authored flow manifest — see docs (§15).',
];

/**
 * The committed, human-readable flow document. Event-centric and deterministic so
 * a PR diff reads naturally. Pass a `title` to label the doc (e.g. the function name).
 */
export function toFlowYaml(kit: EventKit, opts: { title?: string } = {}): string {
  const d = kit.describe();

  const kitBlock: Record<string, unknown> = {
    source: { name: d.source.name, type: d.source.type },
  };
  if (d.platform) kitBlock['platform'] = d.platform;
  kitBlock['plugins'] = d.plugins;

  const events = d.events.map(ev => {
    const out: Record<string, unknown> = { name: ev.name, response: ev.response };
    if (ev.description) out['description'] = ev.description;
    if (ev.owner) out['owner'] = ev.owner;
    if (ev.tags) out['tags'] = ev.tags;
    if (ev.deprecated) out['deprecated'] = true;
    if (ev.runMode) out['runMode'] = ev.runMode;
    if (ev.flowHints) out['flowHints'] = ev.flowHints as Record<string, unknown>;
    out['jobs'] = ev.jobs.map(j => {
      const jo: Record<string, unknown> = { name: j.name };
      if (j.retries !== undefined) jo['retries'] = j.retries;
      if (j.timeoutMs !== undefined) jo['timeoutMs'] = j.timeoutMs;
      if (j.continueOnFailure !== undefined) jo['continueOnFailure'] = j.continueOnFailure;
      if (j.tags) jo['tags'] = j.tags;
      if (j.metadata) jo['metadata'] = j.metadata;
      return jo;
    });
    return out;
  });

  const doc: Record<string, unknown> = { generator: '@hopdrive/eventkit/flow', schema: 1 };
  if (opts.title) doc['title'] = opts.title;
  doc['kit'] = kitBlock;
  doc['events'] = events;

  return BANNER.join('\n') + '\n' + toYaml(doc);
}
