import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { runCli } from '../cli.js';

const here = dirname(fileURLToPath(import.meta.url));
const KIT = resolve(here, 'fixtures/kit.ts');

// Capture stdout/stderr the CLI writes to, and restore after each test.
let out: string[];
let err: string[];
beforeEach(() => {
  out = [];
  err = [];
  vi.spyOn(process.stdout, 'write').mockImplementation((s: string | Uint8Array) => { out.push(String(s)); return true; });
  vi.spyOn(process.stderr, 'write').mockImplementation((s: string | Uint8Array) => { err.push(String(s)); return true; });
});
afterEach(() => vi.restoreAllMocks());

const uniqueOut = (n: string) => resolve(tmpdir(), `eventkit-flow-${n}-${process.pid}.yaml`);

describe('eventkit-flow CLI', () => {
  it('generate --out writes the flow YAML and exits 0', async () => {
    const target = uniqueOut('gen');
    try {
      const code = await runCli(['generate', '--kit', KIT, '--out', target]);
      expect(code).toBe(0);
      expect(existsSync(target)).toBe(true);
      const yaml = readFileSync(target, 'utf8');
      expect(yaml).toContain('# @generated by @hopdrive/eventkit/flow');
      expect(yaml).toContain('name: thing.happened');
      expect(out.join('')).toContain(`✓ wrote ${target}`);
    } finally {
      rmSync(target, { force: true });
    }
  });

  it('generate without --out prints the YAML to stdout', async () => {
    const code = await runCli(['generate', '--kit', KIT]);
    expect(code).toBe(0);
    expect(out.join('')).toContain('# @generated by @hopdrive/eventkit/flow');
  });

  it('check passes (exit 0) when the committed file is up to date', async () => {
    const target = uniqueOut('check-ok');
    try {
      await runCli(['generate', '--kit', KIT, '--out', target]);
      const code = await runCli(['check', '--kit', KIT, '--out', target]);
      expect(code).toBe(0);
      expect(out.join('')).toContain('is up to date');
    } finally {
      rmSync(target, { force: true });
    }
  });

  it('check fails (exit 1) when the file is stale', async () => {
    const target = uniqueOut('check-stale');
    try {
      writeFileSync(target, 'stale: true\n', 'utf8');
      const code = await runCli(['check', '--kit', KIT, '--out', target]);
      expect(code).toBe(1);
      expect(err.join('')).toContain('out of date');
    } finally {
      rmSync(target, { force: true });
    }
  });

  it('check fails (exit 1) when the file is missing', async () => {
    const code = await runCli(['check', '--kit', KIT, '--out', uniqueOut('missing')]);
    expect(code).toBe(1);
    expect(err.join('')).toContain('does not exist');
  });

  it('errors (exit 1) on an unknown command and on a missing --kit', async () => {
    expect(await runCli(['frobnicate', '--kit', KIT])).toBe(1);
    expect(err.join('')).toContain("Unknown command 'frobnicate'");
    err = [];
    expect(await runCli(['generate'])).toBe(1);
    expect(err.join('')).toContain('Missing --kit');
  });
});
