import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { readFileSync, writeFileSync, rmSync, existsSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { runCli } from '../cli.js';

const here = dirname(fileURLToPath(import.meta.url));
const KIT = resolve(here, 'fixtures/kit.ts');

// Capture stdout/stderr the CLI writes to, and restore after each test.
let out: string[];
let err: string[];
beforeEach(() => {
  out = [];
  err = [];
  vi.spyOn(process.stdout, 'write').mockImplementation((s: string | Uint8Array) => { out.push(String(s)); return true; });
  vi.spyOn(process.stderr, 'write').mockImplementation((s: string | Uint8Array) => { err.push(String(s)); return true; });
});
afterEach(() => vi.restoreAllMocks());

const uniqueOut = (n: string) => resolve(tmpdir(), `eventkit-flow-${n}-${process.pid}.yaml`);

describe('eventkit-flow CLI', () => {
  it('generate --out writes the flow YAML and exits 0', async () => {
    const target = uniqueOut('gen');
    try {
      const code = await runCli(['generate', '--kit', KIT, '--out', target]);
      expect(code).toBe(0);
      expect(existsSync(target)).toBe(true);
      const yaml = readFileSync(target, 'utf8');
      expect(yaml).toContain('# @generated by eventkit/flow');
      expect(yaml).toContain('name: thing.happened');
      expect(out.join('')).toContain(`✓ wrote ${target}`);
    } finally {
      rmSync(target, { force: true });
    }
  });

  it('generate without --out prints the YAML to stdout', async () => {
    const code = await runCli(['generate', '--kit', KIT]);
    expect(code).toBe(0);
    expect(out.join('')).toContain('# @generated by eventkit/flow');
  });

  it('check passes (exit 0) when the committed file is up to date', async () => {
    const target = uniqueOut('check-ok');
    try {
      await runCli(['generate', '--kit', KIT, '--out', target]);
      const code = await runCli(['check', '--kit', KIT, '--out', target]);
      expect(code).toBe(0);
      expect(out.join('')).toContain('is up to date');
    } finally {
      rmSync(target, { force: true });
    }
  });

  it('check fails (exit 1) when the file is stale', async () => {
    const target = uniqueOut('check-stale');
    try {
      writeFileSync(target, 'stale: true\n', 'utf8');
      const code = await runCli(['check', '--kit', KIT, '--out', target]);
      expect(code).toBe(1);
      expect(err.join('')).toContain('out of date');
    } finally {
      rmSync(target, { force: true });
    }
  });

  it('check fails (exit 1) when the file is missing', async () => {
    const code = await runCli(['check', '--kit', KIT, '--out', uniqueOut('missing')]);
    expect(code).toBe(1);
    expect(err.join('')).toContain('does not exist');
  });

  it('errors (exit 1) on an unknown command and on a missing --kit', async () => {
    expect(await runCli(['frobnicate', '--kit', KIT])).toBe(1);
    expect(err.join('')).toContain("Unknown command 'frobnicate'");
    err = [];
    expect(await runCli(['generate'])).toBe(1);
    expect(err.join('')).toContain('Missing --kit');
  });

  it('coverage passes when every event has a detector-contract test, fails otherwise', async () => {
    const dir = resolve(tmpdir(), `eventkit-cov-${process.pid}`);
    mkdirSync(dir, { recursive: true });
    const testFile = resolve(dir, 'thing.contract.test.ts');
    try {
      // No test yet → the fixture's 'thing.happened' event is uncovered.
      let code = await runCli(['coverage', '--kit', KIT, '--tests', dir]);
      expect(code).toBe(1);
      expect(err.join('')).toContain('thing.happened');

      // Add a detector-contract test naming the event → covered.
      writeFileSync(testFile, `detectorContract(src, mod, {}); // 'thing.happened'\n`, 'utf8');
      out = [];
      err = [];
      code = await runCli(['coverage', '--kit', KIT, '--tests', dir]);
      expect(code).toBe(0);
      expect(out.join('')).toContain('every registered event has a detector-contract test');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('simulate prints the events that would fire for a fixture payload', async () => {
    const payload = resolve(tmpdir(), `eventkit-sim-${process.pid}.json`);
    try {
      writeFileSync(payload, JSON.stringify({ anything: true }), 'utf8');
      const code = await runCli(['simulate', '--kit', KIT, '--payload', payload]);
      expect(code).toBe(0);
      expect(out.join('')).toContain('Would fire');
      expect(out.join('')).toContain('thing.happened');
      expect(out.join('')).toContain('doThing');
    } finally {
      rmSync(payload, { force: true });
    }
  });

  it('simulate errors (exit 1) when the payload fixture is missing', async () => {
    const code = await runCli(['simulate', '--kit', KIT, '--payload', resolve(tmpdir(), 'nope-does-not-exist.json')]);
    expect(code).toBe(1);
    expect(err.join('')).toContain('not found');
  });

  it('simulate errors (exit 1) when --payload is omitted', async () => {
    const code = await runCli(['simulate', '--kit', KIT]);
    expect(code).toBe(1);
    expect(err.join('')).toContain('requires --payload');
  });

  it('simulate errors (exit 1) on malformed JSON', async () => {
    const payload = resolve(tmpdir(), `eventkit-sim-bad-${process.pid}.json`);
    try {
      writeFileSync(payload, '{ not: valid json', 'utf8');
      const code = await runCli(['simulate', '--kit', KIT, '--payload', payload]);
      expect(code).toBe(1);
      expect(err.join('')).toContain('could not parse');
    } finally {
      rmSync(payload, { force: true });
    }
  });

  it('simulate reports when no events would fire', async () => {
    const kitNoFire = resolve(here, 'fixtures/kit-nofire.ts');
    const payload = resolve(tmpdir(), `eventkit-sim-none-${process.pid}.json`);
    try {
      writeFileSync(payload, JSON.stringify({ x: 1 }), 'utf8');
      const code = await runCli(['simulate', '--kit', kitNoFire, '--payload', payload]);
      expect(code).toBe(0);
      expect(out.join('')).toContain('No events would fire');
    } finally {
      rmSync(payload, { force: true });
    }
  });

  it('simulate surfaces a detector crash on stderr (still exit 0)', async () => {
    const kitCrash = resolve(here, 'fixtures/kit-crash.ts');
    const payload = resolve(tmpdir(), `eventkit-sim-crash-${process.pid}.json`);
    try {
      writeFileSync(payload, JSON.stringify({ x: 1 }), 'utf8');
      const code = await runCli(['simulate', '--kit', kitCrash, '--payload', payload]);
      expect(code).toBe(0);
      expect(err.join('')).toContain('detector threw');
    } finally {
      rmSync(payload, { force: true });
    }
  });
});
