import { describe, it, expect } from 'vitest';
import { createEventKit, defineEvent, job } from '../../index.js';
import { hasuraEvent } from '../../plugins/source-hasura.js';
import { loopGuard } from '../../plugins/loop-guard/index.js';
import { netlifyPlatform } from '../../plugins/platforms.js';
import { describeKit, toFlowGraph, toFlowYaml } from '../graph.js';
import { toYaml } from '../yaml.js';

// A kit exercising all three response kinds, job options, side-effect metadata,
// and module metadata — so introspection has something to reflect.
function buildKit() {
  const fireAndForget = defineEvent({
    name: 'appointment.ready',
    detector: hasuraEvent.detector(() => true),
    metadata: { description: 'Appointment became ready', owner: 'scheduling', flowHints: { flow: 'mobile-service' } },
    jobs: [
      job(() => { throw new Error('describe must NOT run jobs'); }, { name: 'sendOfferSMS', metadata: { sideEffect: 'sms' } }),
      job(() => {}, { name: 'notifyOrg', retries: 3 }),
    ],
  });

  const requestResponse = defineEvent({
    name: 'billing.quote',
    detector: hasuraEvent.detector(() => true),
    response: { fromRequest: () => ({ ok: true }) },
    jobs: [job(() => {}, { name: 'logQuote' })],
  });

  const resultDriven = defineEvent({
    name: 'billing.charge',
    detector: hasuraEvent.detector(() => true),
    response: { fromJobs: (_ctx, { ok }) => ({ ok }) },
    jobs: [job(() => {}, { name: 'charge' })],
  });

  return createEventKit(hasuraEvent)
    .use(netlifyPlatform)
    .use(loopGuard, { codec: { separator: '|' } })
    .registerEvents([fireAndForget, requestResponse, resultDriven]);
}

describe('kit.describe()', () => {
  it('reflects source, platform, plugins, and every event with its static jobs — running nothing', () => {
    const d = describeKit(buildKit());

    expect(d.source).toEqual({ name: 'source-hasura-event', type: 'database' });
    expect(d.platform).toBe('platform-netlify');
    expect(d.plugins).toEqual(['loop-guard']); // source + platform excluded

    const ready = d.events.find(e => e.name === 'appointment.ready')!;
    expect(ready.response).toBe('none');
    expect(ready.description).toBe('Appointment became ready');
    expect(ready.owner).toBe('scheduling');
    expect(ready.flowHints).toEqual({ flow: 'mobile-service' });
    expect(ready.jobs.map(j => j.name)).toEqual(['sendOfferSMS', 'notifyOrg']);
    expect(ready.jobs[1]).toMatchObject({ name: 'notifyOrg', retries: 3 });
    expect(ready.jobs[0]!.metadata).toEqual({ sideEffect: 'sms' });

    expect(d.events.find(e => e.name === 'billing.quote')!.response).toBe('from-request');
    expect(d.events.find(e => e.name === 'billing.charge')!.response).toBe('from-jobs');
  });

  it('is pure — introspecting does not execute a job (the throwing job never runs)', () => {
    const kit = buildKit();
    expect(() => kit.describe()).not.toThrow();
    expect(() => toFlowYaml(kit)).not.toThrow();
  });
});

describe('toFlowGraph()', () => {
  it('emits source/event/job/sideEffect nodes and edges in the manifest vocabulary', () => {
    const { nodes, edges } = toFlowGraph(buildKit());

    expect(nodes.find(n => n.kind === 'source')).toMatchObject({ id: 'source', sourceFunction: 'source-hasura-event' });
    expect(nodes.find(n => n.id === 'event:appointment.ready')).toMatchObject({ kind: 'event', eventName: 'appointment.ready' });
    expect(nodes.find(n => n.id === 'job:appointment.ready:notifyOrg')).toMatchObject({ kind: 'job', jobName: 'notifyOrg' });

    // side-effect node + edge derived from job metadata.sideEffect
    expect(nodes.find(n => n.kind === 'sideEffect')).toMatchObject({ metadata: { sideEffect: 'sms' } });
    expect(edges).toContainEqual({ from: 'source', to: 'event:appointment.ready' });
    expect(edges).toContainEqual({ from: 'event:appointment.ready', to: 'job:appointment.ready:sendOfferSMS' });
    expect(edges).toContainEqual({ from: 'event:appointment.ready', to: 'job:appointment.ready:notifyOrg' });
  });
});

describe('toFlowYaml()', () => {
  it('is deterministic and carries the generated banner + structure', () => {
    const kit = buildKit();
    const a = toFlowYaml(kit);
    const b = toFlowYaml(kit);
    expect(a).toBe(b); // stable → clean diffs

    expect(a).toContain('# @generated by eventkit/flow');
    expect(a).toContain('name: source-hasura-event');
    expect(a).toContain('platform: platform-netlify');
    expect(a).toContain('plugins: [loop-guard]'); // scalar array → flow style
    expect(a).toContain('name: appointment.ready');
    expect(a).toContain('response: from-request');
    expect(a).toContain('retries: 3');
  });
});

describe('toYaml (emitter)', () => {
  it('handles scalars, flow arrays, block arrays of objects, and nested maps', () => {
    const out = toYaml({
      a: 'plain',
      b: 42,
      c: true,
      list: ['x', 'y'],
      empty: [],
      nested: { deep: 'value' },
      items: [{ name: 'one', n: 1 }, { name: 'two' }],
      skipMe: undefined,
      alsoSkip: null,
    });
    expect(out).toContain('a: plain');
    expect(out).toContain('b: 42');
    expect(out).toContain('c: true');
    expect(out).toContain('list: [x, y]');
    expect(out).toContain('empty: []');
    expect(out).toContain('nested:\n  deep: value');
    expect(out).toContain('items:\n  - name: one\n    n: 1');
    expect(out).not.toContain('skipMe');
    expect(out).not.toContain('alsoSkip');
  });

  it('quotes strings that would be misread as YAML', () => {
    const out = toYaml({ ver: '1.0', bool: 'true', colon: 'a: b', at: '@handle', ok: 'event.name' });
    expect(out).toContain('ver: "1.0"'); // numeric-looking
    expect(out).toContain('bool: "true"'); // reserved word
    expect(out).toContain('colon: "a: b"'); // key/value ambiguity
    expect(out).toContain('at: "@handle"'); // leading indicator
    expect(out).toContain('ok: event.name'); // safe → unquoted
  });
});
